FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html  /usr/share/nginx/html

ENV MY_NAME Nobody

COPY ./entrypoint.sh /tmp
RUN chmod u+x /tmp/entrypoint.sh
ENTRYPOINT ["/tmp/entrypoint.sh"]

